# Generated by Django 5.2.18 on 2026-10-07 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('show_time', models.DateTimeField()),
                ('hide_time', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
                ('maintenance', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('facebook_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MirroredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('path', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('resource', models.TextField()),
                ('small', models.CharField(blank=True, max_length=500, null=True)),
                ('medium', models.CharField(blank=True, max_length=500, null=True)),
                ('large', models.CharField(blank=True, max_length=500, null=True)),
                ('hires', models.CharField(blank=True, max_length=500, null=True)),
                ('author_name', models.CharField(blank=True, max_length=200, null=True)),
                ('author_url', models.CharField(blank=True, max_length=500, null=True)),
                ('license', models.IntegerField(choices=[(0, 'Unknown'), (1, 'None'), (10, 'Cc By 30'), (11, 'Cc By Sa 30'), (12, 'Cc By Nd 30'), (20, 'Youtube'), (30, 'Facebook'), (40, 'Internal Text'), (41, 'Internal Picture'), (50, 'Wikipedia'), (60, 'Twitter')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('legacy', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('join_date', models.DateTimeField(blank=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('confirmed_tos_version', models.BigIntegerField(default=0)),
                ('admin', models.BooleanField(default=False)),
                ('banned', models.BooleanField(default=False)),
                ('last_announcement', models.DateTimeField(blank=True, null=True)),
                ('subscribe_own_assignments', models.BooleanField(default=True)),
                ('notify_other_activity', models.BooleanField(default=True)),
                ('notify_activity_reward', models.BooleanField(default=True)),
                ('notify_other_activity_reward', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('typ', models.IntegerField(choices=[(0, 'Unknown'), (10, 'Other Activity'), (20, 'Reward Activity'), (30, 'Reward Other Activity')])),
                ('timestamp', models.DateTimeField()),
                ('emailed', models.DateTimeField(blank=True, null=True)),
                ('html', models.TextField()),
                ('values', models.JSONField(default=list)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='mastery.account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('registration_timestamp', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=20, null=True)),
                ('timezone', models.FloatField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('founder', models.BooleanField(blank=True, null=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='own_person', to='mastery.account')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mastery.city')),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('typ', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=500)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='mastery.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('rewards_sum', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('abuse_reports_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('reward_due_date', models.DateTimeField()),
                ('rewarded', models.IntegerField(blank=True, null=True)),
                ('abuse_reports_count', models.IntegerField(default=0)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='mastery.achievement')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='mastery.assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='mastery.person'),
        ),
        migrations.AddField(
            model_name='account',
            name='cloak',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mastery.person'),
        ),
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mastery.person'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('positive', models.BooleanField()),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='mastery.activity')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('typ', models.IntegerField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Video')])),
                ('authentic', models.BooleanField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='mastery.activity')),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.resource')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='mastery.assignment')),
                ('donating_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('creation_timestamp', models.DateTimeField()),
                ('title', models.CharField(max_length=40)),
                ('abuse_reports_count', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.person')),
                ('description', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.resource')),
                ('picture', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='mastery.skill'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.skill'),
        ),
        migrations.CreateModel(
            name='AbuseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='mastery.activity')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='mastery.assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mastery.person')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='mastery.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mastery.account')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='mastery.assignment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('legacy', False), ('user__isnull', True), _connector='OR'), name='legacy_account_has_no_login'),
        ),
        migrations.AddConstraint(
            model_name='abusereport',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('activity__isnull', True), ('assignment__isnull', True), ('skill__isnull', False)), models.Q(('activity__isnull', True), ('assignment__isnull', False), ('skill__isnull', True)), models.Q(('activity__isnull', False), ('assignment__isnull', True), ('skill__isnull', True)), _connector='OR'), name='abuse_report_has_one_target'),
        ),
    ]
